using System.Text;
using Chrysalis.Codec.CodeGen.Blueprint.Analysis;

namespace Chrysalis.Codec.CodeGen.Blueprint.Generation;

/// <summary>
/// Generates C# source text from resolved blueprint types.
/// </summary>
/// <remarks>
/// Initializes a new instance of the <see cref="CSharpEmitter"/> class.
/// </remarks>
internal sealed class CSharpEmitter(string ns)
{
    private readonly string _namespace = ns;

    /// <summary>
    /// Generates all type definitions as a single source file.
    /// </summary>
    public string EmitAllTypes(Dictionary<string, ResolvedType> resolvedTypes)
    {
        StringBuilder sb = new();
        EmitHeader(sb);
        _ = sb.AppendLine($"namespace {_namespace};");
        _ = sb.AppendLine();

        foreach (KeyValuePair<string, ResolvedType> kv in resolvedTypes)
        {
            ResolvedType type = kv.Value;
            EmitType(sb, type);
        }

        return sb.ToString();
    }

    private static void EmitHeader(StringBuilder sb)
    {
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine("#pragma warning disable CS1591");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using Chrysalis.Codec.Serialization;");
        _ = sb.AppendLine("using Chrysalis.Codec.Serialization.Attributes;");
        _ = sb.AppendLine("using Chrysalis.Codec.Types;");
        _ = sb.AppendLine("using Chrysalis.Codec.Types.Cardano.Core.Common;");
        _ = sb.AppendLine();
    }

    private static void EmitType(StringBuilder sb, ResolvedType type)
    {
        switch (type.Category)
        {
            case TypeCategory.SingleConstructor:
                EmitSingleConstructor(sb, type);
                break;
            case TypeCategory.Union:
                EmitUnion(sb, type);
                break;
            case TypeCategory.Tuple:
                EmitTuple(sb, type);
                break;
            case TypeCategory.PrimitiveBytes:
                break;
            case TypeCategory.PrimitiveInteger:
                break;
            case TypeCategory.PrimitiveBool:
                break;
            case TypeCategory.PrimitiveData:
                break;
            case TypeCategory.Option:
                break;
            case TypeCategory.List:
                break;
            case TypeCategory.Ref:
                break;
            default:
                break;
        }
    }

    private static void EmitSingleConstructor(StringBuilder sb, ResolvedType type)
    {
        if (type.Constructors == null || type.Constructors.Count == 0)
        {
            return;
        }

        ResolvedConstructor ctor = type.Constructors[0];
        _ = sb.AppendLine("[CborSerializable]");
        _ = sb.AppendLine($"[CborConstr({ctor.Index})]");
        if (ctor.Fields.Count > 0)
        {
            _ = sb.AppendLine("[CborIndefinite]");
        }

        if (ctor.Fields.Count == 0)
        {
            _ = sb.AppendLine($"public partial record {type.TypeName}() : CborRecord;");
        }
        else
        {
            _ = sb.Append($"public partial record {type.TypeName}(");
            _ = sb.AppendLine();
            EmitFieldParameters(sb, ctor.Fields);
            _ = sb.AppendLine(") : CborRecord;");
        }

        _ = sb.AppendLine();
    }

    private static void EmitUnion(StringBuilder sb, ResolvedType type)
    {
        string interfaceName = "I" + type.TypeName;

        _ = sb.AppendLine("[CborSerializable]");
        _ = sb.AppendLine("[CborConstr]");
        _ = sb.AppendLine("[CborUnion]");
        _ = sb.AppendLine($"public partial interface {interfaceName} : ICborType;");
        _ = sb.AppendLine();

        if (type.Constructors == null)
        {
            return;
        }

        foreach (ResolvedConstructor ctor in type.Constructors)
        {
            _ = sb.AppendLine("[CborSerializable]");
            _ = sb.AppendLine($"[CborConstr({ctor.Index})]");
            if (ctor.Fields.Count > 0)
            {
                _ = sb.AppendLine("[CborIndefinite]");
            }

            if (ctor.Fields.Count == 0)
            {
                _ = sb.AppendLine($"public partial record {ctor.Name}() : CborRecord, {interfaceName};");
            }
            else
            {
                _ = sb.Append($"public partial record {ctor.Name}(");
                _ = sb.AppendLine();
                EmitFieldParameters(sb, ctor.Fields);
                _ = sb.AppendLine($") : CborRecord, {interfaceName};");
            }

            _ = sb.AppendLine();
        }
    }

    private static void EmitTuple(StringBuilder sb, ResolvedType type)
    {
        if (type.TupleFields == null || type.TupleFields.Count == 0)
        {
            return;
        }

        _ = sb.AppendLine("[CborSerializable]");
        _ = sb.AppendLine("[CborList]");
        _ = sb.AppendLine("[CborIndefinite]");
        _ = sb.Append($"public partial record {type.TypeName}(");
        _ = sb.AppendLine();
        EmitFieldParameters(sb, type.TupleFields);
        _ = sb.AppendLine(") : CborRecord;");
        _ = sb.AppendLine();
    }

    private static void EmitFieldParameters(StringBuilder sb, List<ResolvedField> fields)
    {
        for (int i = 0; i < fields.Count; i++)
        {
            ResolvedField field = fields[i];
            string nullable = field.IsNullable ? "?" : "";
            string comma = i < fields.Count - 1 ? "," : "";
            _ = sb.AppendLine($"    [CborOrder({field.Order})] {field.CSharpType}{nullable} {field.Name}{comma}");
        }
    }
}
