using System.Text;
using Chrysalis.Codec.CodeGen.Blueprint.Models;

namespace Chrysalis.Codec.CodeGen.Blueprint.Generation;

/// <summary>
/// Generates static validator wrapper classes from blueprint validators.
/// </summary>
/// <remarks>
/// Initializes a new instance of the <see cref="ValidatorEmitter"/> class.
/// </remarks>
internal sealed class ValidatorEmitter(string ns, string plutusVersion)
{
    private readonly string _namespace = ns;
    private readonly string _plutusVersion = plutusVersion;

    /// <summary>
    /// Generates all validator wrappers as a single source file.
    /// </summary>
    public string EmitAllValidators(List<BlueprintValidator> validators)
    {
        StringBuilder sb = new();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine("#pragma warning disable CS1591");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using Chrysalis.Codec.Types.Cardano.Core.Scripts;");
        _ = sb.AppendLine("using Chrysalis.Wallet.Models.Enums;");
        _ = sb.AppendLine("using WalletAddress = Chrysalis.Wallet.Models.Addresses.Address;");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"namespace {_namespace};");
        _ = sb.AppendLine();

        foreach (BlueprintValidator validator in validators)
        {
            EmitValidator(sb, validator);
        }

        return sb.ToString();
    }

    private void EmitValidator(StringBuilder sb, BlueprintValidator validator)
    {
        string className = NamingConventions.ValidatorClassName(validator.Title);
        string scriptType = GetScriptType(_plutusVersion);
        string scriptTag = GetScriptTag(_plutusVersion);

        _ = sb.AppendLine($"/// <summary>");
        _ = sb.AppendLine($"/// Validator: {validator.Title}");
        _ = sb.AppendLine($"/// </summary>");
        _ = sb.AppendLine($"public static class {className}");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine($"    /// <summary>Hex-encoded compiled UPLC flat bytes.</summary>");
        _ = sb.AppendLine($"    public const string CompiledCode = \"{validator.CompiledCode}\";");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"    /// <summary>Blake2b-224 script hash (56 hex chars).</summary>");
        _ = sb.AppendLine($"    public const string Hash = \"{validator.Hash}\";");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"    /// <summary>Plutus language version.</summary>");
        _ = sb.AppendLine($"    public const string PlutusVersion = \"{_plutusVersion}\";");
        _ = sb.AppendLine();

        // Script property
        _ = sb.AppendLine($"    private static IScript? _script;");
        _ = sb.AppendLine($"    /// <summary>The compiled Plutus script, ready for use in transactions.</summary>");
        _ = sb.AppendLine($"    public static IScript Script => _script ??= {scriptType}.Create({scriptTag}, System.Convert.FromHexString(CompiledCode));");
        _ = sb.AppendLine();

        // Address helpers
        _ = sb.AppendLine($"    /// <summary>Enterprise script address on mainnet.</summary>");
        _ = sb.AppendLine($"    public static WalletAddress MainnetAddress => WalletAddress.FromScriptHash(NetworkType.Mainnet, Hash);");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"    /// <summary>Enterprise script address on testnet.</summary>");
        _ = sb.AppendLine($"    public static WalletAddress TestnetAddress => WalletAddress.FromScriptHash(NetworkType.Testnet, Hash);");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"    /// <summary>Enterprise script address for the given network.</summary>");
        _ = sb.AppendLine($"    public static WalletAddress GetAddress(NetworkType network) => WalletAddress.FromScriptHash(network, Hash);");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"    /// <summary>Script address with key-based stake delegation.</summary>");
        _ = sb.AppendLine($"    public static WalletAddress GetAddress(NetworkType network, byte[] stakeKeyHash) =>");
        _ = sb.AppendLine($"        WalletAddress.FromScriptHashWithStake(network, System.Convert.FromHexString(Hash), stakeKeyHash);");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"    /// <summary>Script address with script-based stake delegation.</summary>");
        _ = sb.AppendLine($"    public static WalletAddress GetAddress(NetworkType network, byte[] stakeScriptHash, bool isStakeScript) =>");
        _ = sb.AppendLine($"        new WalletAddress(network, isStakeScript ? AddressType.ScriptPaymentWithScriptDelegation : AddressType.ScriptPaymentWithDelegation,");
        _ = sb.AppendLine($"            System.Convert.FromHexString(Hash), stakeScriptHash);");

        _ = sb.AppendLine("}");
        _ = sb.AppendLine();
    }

    private static string GetScriptType(string version) => version switch
    {
        "v1" => "PlutusV1Script",
        "v2" => "PlutusV2Script",
        "v3" => "PlutusV3Script",
        _ => "PlutusV3Script"
    };

    private static string GetScriptTag(string version) => version switch
    {
        "v1" => "1",
        "v2" => "2",
        "v3" => "3",
        _ => "3"
    };
}
