using System.Text;
using Chrysalis.Blueprint.CodeGen.Models;

namespace Chrysalis.Blueprint.CodeGen.Generation;

/// <summary>
/// Generates static validator wrapper classes from blueprint validators.
/// </summary>
/// <remarks>
/// Initializes a new instance of the <see cref="ValidatorEmitter"/> class.
/// </remarks>
internal sealed class ValidatorEmitter(string ns, string plutusVersion)
{
    private readonly string _namespace = ns;
    private readonly string _plutusVersion = plutusVersion;

    /// <summary>
    /// Generates all validator wrappers as a single source file.
    /// </summary>
    public string EmitAllValidators(List<BlueprintValidator> validators)
    {
        StringBuilder sb = new();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#pragma warning disable CS1591");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"namespace {_namespace};");
        _ = sb.AppendLine();

        foreach (BlueprintValidator validator in validators)
        {
            EmitValidator(sb, validator);
        }

        return sb.ToString();
    }

    private void EmitValidator(StringBuilder sb, BlueprintValidator validator)
    {
        string className = NamingConventions.ValidatorClassName(validator.Title);

        _ = sb.AppendLine($"/// <summary>");
        _ = sb.AppendLine($"/// Validator: {validator.Title}");
        _ = sb.AppendLine($"/// </summary>");
        _ = sb.AppendLine($"public static class {className}");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine($"    /// <summary>Hex-encoded compiled UPLC flat bytes.</summary>");
        _ = sb.AppendLine($"    public const string CompiledCode = \"{validator.CompiledCode}\";");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"    /// <summary>Blake2b-224 script hash.</summary>");
        _ = sb.AppendLine($"    public const string Hash = \"{validator.Hash}\";");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"    /// <summary>Plutus language version.</summary>");
        _ = sb.AppendLine($"    public const string PlutusVersion = \"{_plutusVersion}\";");
        _ = sb.AppendLine("}");
        _ = sb.AppendLine();
    }
}
