using System.Text;
using Microsoft.CodeAnalysis;

namespace Chrysalis.Cbor.CodeGen;

public sealed partial class CborSerializerCodeGen
{
    private interface ICborSerializerEmitter
    {
        StringBuilder EmitWriter(StringBuilder sb, SerializableTypeMetadata metadata);
        StringBuilder EmitReader(StringBuilder sb, SerializableTypeMetadata metadata, bool useExistingReader);
    }

    private static partial class Emitter
    {
        public const string GenericSerializationUtilFullname = "global::Chrysalis.Cbor.Serialization.Utils.GenericSerializationUtil";
        public const string CborEncodeValueFullName = "global::Chrysalis.Cbor.Types.CborEncodedValue";

        public static void EmitSerializerAndMetadata(SourceProductionContext context, SerializableTypeMetadata metadata)
        {
            // Metadata emission
            context.AddSource($"{metadata?.FullyQualifiedName.Replace("<", "`").Replace(">", "`")}.Metadata.g.cs", metadata?.ToString()!);

            // Serializer emission
            StringBuilder sb = new();
            _ = sb.AppendLine("// <auto-generated/>");
            _ = sb.AppendLine("#pragma warning disable CS0109, CS8669");
            _ = sb.AppendLine();
            _ = sb.AppendLine("using System.Formats.Cbor;");
            _ = sb.AppendLine();

            if (metadata?.Namespace is not null)
            {
                _ = sb.AppendLine($"namespace {metadata?.Namespace};");
            }

            _ = sb.AppendLine($"public partial {metadata?.Keyword} {metadata?.Indentifier}");
            _ = sb.AppendLine("{");

            _ = EmitSerializableTypeReader(sb, metadata!);

            _ = sb.AppendLine();

            _ = EmitSerializableTypeWriter(sb, metadata!);

            _ = sb.AppendLine("}");
            _ = sb.AppendLine();
            _ = sb.AppendLine("#pragma warning restore CS0109, CS8669");

            context.AddSource($"{metadata?.FullyQualifiedName.Replace("<", "`").Replace(">", "`")}.Serializer.g.cs", sb.ToString());
        }

        private static ICborSerializerEmitter GetEmitter(SerializableTypeMetadata metadata)
        {
            return metadata.SerializationType switch
            {
                SerializationType.Constr => new ConstructorEmitter(),
                SerializationType.Container => new ContainerEmitter(),
                SerializationType.List => new ListEmitter(),
                SerializationType.Map => new MapEmitter(),
                SerializationType.Union => new UnionEmitter(),
                _ => throw new NotSupportedException($"Serialization type {metadata.SerializationType} is not supported.")
            };
        }

        public static int ResolveTag(int? index)
        {
            if (index is null or < 0)
            {
                return -1;
            }
            else
            {
                int finalIndex = index > 6 ? 1280 - 7 : 121;
                return finalIndex + index.Value;
            }
        }

        private static bool IsReadOnlyMemoryByteType(string type)
        {
            return type.Replace("?", "") is "ReadOnlyMemory<byte>" or "System.ReadOnlyMemory<byte>" or "global::System.ReadOnlyMemory<byte>";
        }

        private static bool IsPrimitiveType(string type)
        {
            return type.Replace("?", "") switch
            {
                "bool" => true,
                "int" => true,
                "long" => true,
                "ulong" => true,
                "uint" => true,
                "float" => true,
                "double" => true,
                "decimal" => true,
                "string" => true,
                "byte[]" => true,
                "ReadOnlyMemory<byte>" => true,
                "System.ReadOnlyMemory<byte>" => true,
                "global::System.ReadOnlyMemory<byte>" => true,
                "CborEncodedValue" => true,
                "Chrysalis.Cbor.Types.Primitives.CborEncodedValue" => true,
                "global::Chrysalis.Cbor.Types.Primitives.CborEncodedValue" => true,
                "CborLabel" => true,
                "Chrysalis.Cbor.Types.CborLabel" => true,
                "global::Chrysalis.Cbor.Types.CborLabel" => true,
                _ => false
            };
        }
    }
}
