using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Chrysalis.Codec.CodeGen;

public sealed partial class CborSerializerCodeGen
{
    private interface ICborSerializerEmitter
    {
        StringBuilder EmitWriter(StringBuilder sb, SerializableTypeMetadata metadata);
        StringBuilder EmitReader(StringBuilder sb, SerializableTypeMetadata metadata);
    }

    internal static partial class Emitter
    {
        public const string GenericSerializationUtilFullname = "global::Chrysalis.Codec.Serialization.GenericSerializationUtil";
        public const string CborEncodeValueFullName = "global::Chrysalis.Codec.Types.CborEncodedValue";

        public static void EmitSerializerAndMetadata(SourceProductionContext context, SerializableTypeMetadata metadata)
        {
            string hintName = metadata?.FullyQualifiedName.Replace("global::", "").Replace("<", "`").Replace(">", "`") ?? "Unknown";
            context.AddSource($"{hintName}.Metadata.g.cs", metadata?.ToString()!);

            StringBuilder sb = new();
            _ = sb.AppendLine("// <auto-generated/>");
            _ = sb.AppendLine("#pragma warning disable CS0109, CS8669");
            _ = sb.AppendLine();
            _ = sb.AppendLine("using SAIB.Cbor.Serialization;");
            _ = sb.AppendLine("using System.Buffers;");
            _ = sb.AppendLine("using Chrysalis.Codec.Types;");
            _ = sb.AppendLine("using Chrysalis.Codec.Serialization;");
            _ = sb.AppendLine();

            if (metadata?.Namespace is not null)
            {
                _ = sb.AppendLine($"namespace {metadata?.Namespace};");
            }

            string partialKeyword = metadata?.IsRecordStruct == true
                ? "readonly partial record struct"
                : $"partial {metadata?.Keyword}";
            _ = sb.AppendLine($"public {partialKeyword} {metadata?.Indentifier}");
            _ = sb.AppendLine("{");

            // For record struct types, emit internal field slices and ICborType implementation
            if (metadata?.IsRecordStruct == true)
            {
                _ = EmitRecordStructFields(sb, metadata);
            }

            if (metadata?.SerializationType is SerializationType.Map)
            {
                bool isIntKey = metadata.Properties[0].PropertyKeyInt is not null;
                _ = sb.AppendLine($"static Dictionary<{(isIntKey ? "int" : "string")}, Type> TypeMapping = new()");
                _ = sb.AppendLine("{");

                List<SerializablePropertyMetadata> properties = [.. metadata.Properties];
                for (int i = 0; i < properties.Count; i++)
                {
                    SerializablePropertyMetadata prop = properties[i];
                    string? keyValue = isIntKey ? prop.PropertyKeyInt?.ToString(CultureInfo.InvariantCulture) : prop.PropertyKeyString;
                    // Strip nullable annotation for typeof() — typeof(T?) is invalid for reference types
                    string typeForTypeof = prop.PropertyTypeFullName.TrimEnd('?');

                    _ = i == properties.Count - 1
                        ? sb.AppendLine($"  {{{keyValue}, typeof({typeForTypeof})}}")
                        : sb.AppendLine($"  {{{keyValue}, typeof({typeForTypeof})}},");
                }

                _ = sb.AppendLine("};");
                _ = sb.AppendLine();
            }

            if (metadata?.SerializationType is SerializationType.Map)
            {
                bool isIntKey = metadata.Properties[0].PropertyKeyInt is not null;
                _ = sb.AppendLine($"static Dictionary<string, {(isIntKey ? "int" : "string")}> KeyMapping = new()");
                _ = sb.AppendLine("{");

                List<SerializablePropertyMetadata> properties = [.. metadata.Properties];
                for (int i = 0; i < properties.Count; i++)
                {
                    SerializablePropertyMetadata prop = properties[i];
                    string? keyValue = $"\"{prop.PropertyName}\"";
                    string? value = isIntKey ? prop.PropertyKeyInt?.ToString(CultureInfo.InvariantCulture) : prop.PropertyKeyString;

                    _ = i == properties.Count - 1
                        ? sb.AppendLine($"  {{{keyValue}, {value}}}")
                        : sb.AppendLine($"  {{{keyValue}, {value}}},");
                }

                _ = sb.AppendLine("};");
                _ = sb.AppendLine();
            }

            _ = EmitSerializableTypeReader(sb, metadata!);

            _ = sb.AppendLine();

            _ = EmitSerializableTypeWriter(sb, metadata!);

            _ = sb.AppendLine();
            _ = EmitCreateMethod(sb, metadata!);

            _ = sb.AppendLine("}");
            _ = sb.AppendLine();
            _ = sb.AppendLine("#pragma warning restore CS0109, CS8669");

            context.AddSource($"{hintName}.Serializer.g.cs", sb.ToString());
        }

        private static StringBuilder EmitRecordStructFields(StringBuilder sb, SerializableTypeMetadata metadata)
        {
            // Internal field slices
            _ = sb.AppendLine("internal ReadOnlyMemory<byte> _raw { get; init; }");
            for (int i = 0; i < metadata.Properties.Count; i++)
            {
                _ = sb.AppendLine($"internal ReadOnlyMemory<byte> _field{i} {{ get; init; }}");
            }
            _ = sb.AppendLine("internal bool _isIndefinite { get; init; }");
            _ = sb.AppendLine("internal int _constrIndex { get; init; }");
            _ = sb.AppendLine();

            // ICborType implementation
            _ = sb.AppendLine("/// <inheritdoc/>");
            _ = sb.AppendLine("public ReadOnlyMemory<byte> Raw => _raw;");
            _ = sb.AppendLine("/// <inheritdoc/>");
            _ = sb.AppendLine("public int ConstrIndex => _constrIndex;");
            _ = sb.AppendLine("/// <inheritdoc/>");
            _ = sb.AppendLine("public bool IsIndefinite => _isIndefinite;");
            _ = sb.AppendLine();

            // Partial property implementations
            for (int i = 0; i < metadata.Properties.Count; i++)
            {
                SerializablePropertyMetadata prop = metadata.Properties[i];
                _ = EmitPartialPropertyAccessor(sb, prop, i);
            }
            _ = sb.AppendLine();

            return sb;
        }

        private static StringBuilder EmitPartialPropertyAccessor(StringBuilder sb, SerializablePropertyMetadata prop, int fieldIndex)
        {
            string cleanType = prop.PropertyType.Replace("?", "");
            string fieldRef = $"_field{fieldIndex}";
            // Use fully qualified name for generated partial property to avoid missing using directives
            string fqType = prop.PropertyTypeFullName;

            if (IsPrimitiveType(cleanType))
            {
                _ = EmitPrimitivePartialProperty(sb, prop, cleanType, fieldRef, fqType);
            }
            else if (prop.IsList)
            {
                _ = EmitListPartialProperty(sb, prop, fieldRef, fqType);
            }
            else if (prop.IsMap)
            {
                _ = EmitMapPartialProperty(sb, prop, fieldRef, fqType);
            }
            else if (prop.UnionHints.Count > 0 && prop.UnionHintDiscriminantProperty is not null)
            {
                // Union hint dispatch — read discriminant property, switch to concrete type
                string nonNullType = fqType.Replace("?", "");
                _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName}");
                _ = sb.AppendLine("{");
                _ = sb.AppendLine("get");
                _ = sb.AppendLine("{");
                _ = sb.AppendLine($"return {prop.UnionHintDiscriminantProperty} switch");
                _ = sb.AppendLine("{");
                foreach (KeyValuePair<int, string> hint in prop.UnionHints)
                {
                    _ = sb.AppendLine($"    {hint.Key} => ({fqType}){hint.Value}.Read({fieldRef}),");
                }
                _ = sb.AppendLine($"    _ => ({fqType}){nonNullType}.Read({fieldRef})");
                _ = sb.AppendLine("};");
                _ = sb.AppendLine("}");
                _ = sb.AppendLine("}");
            }
            else if (prop.CborMaybeIndefListItemTypeFullName is not null)
            {
                _ = EmitMaybeIndefListPartialProperty(sb, prop, fieldRef, fqType);
            }
            else if (prop.IsOpenGeneric)
            {
                if (prop.IsTypeNullable)
                {
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName} {{ get => {fieldRef}.Length == 0 || {fieldRef}.Span[0] is 0xF6 or 0xF7 ? default({fqType}) : {GenericSerializationUtilFullname}.ReadAnyWithConsumed<{fqType.Replace("?", "")}>({fieldRef}, out _); }}");
                }
                else
                {
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName} {{ get => {GenericSerializationUtilFullname}.ReadAnyWithConsumed<{fqType}>({fieldRef}, out _); }}");
                }
            }
            else
            {
                // Complex type — call its Read() method on the slice
                string nonNullType = fqType.Replace("?", "");
                if (prop.IsTypeNullable)
                {
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName} {{ get => {fieldRef}.Length == 0 || {fieldRef}.Span[0] is 0xF6 or 0xF7 ? default({fqType}) : {nonNullType}.Read({fieldRef}); }}");
                }
                else
                {
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName} {{ get => {nonNullType}.Read({fieldRef}); }}");
                }
            }

            return sb;
        }

        private static StringBuilder EmitListPartialProperty(StringBuilder sb, SerializablePropertyMetadata prop, string fieldRef, string fqType)
        {
            string itemType = prop.ListItemTypeFullName!;
            string cleanItemType = itemType.Replace("?", "");

            _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName}");
            _ = sb.AppendLine("{");
            _ = sb.AppendLine("get");
            _ = sb.AppendLine("{");

            if (prop.IsTypeNullable)
            {
                _ = sb.AppendLine($"if ({fieldRef}.Length == 0 || {fieldRef}.Span[0] is 0xF6 or 0xF7) return default;");
            }

            _ = sb.AppendLine($"var _r = new CborReader({fieldRef}.Span);");
            _ = sb.AppendLine("_r.ReadBeginArray();");
            _ = sb.AppendLine("int _size = _r.ReadSize();");
            _ = sb.AppendLine($"var _list = new global::System.Collections.Generic.List<{itemType}>();");
            _ = sb.AppendLine("int _remaining = _size;");
            _ = sb.AppendLine("while (_size == -1 ? (_r.Buffer.Length > 0 && _r.Buffer[0] != 0xFF) : _remaining > 0)");
            _ = sb.AppendLine("{");

            if (prop.IsListItemTypeOpenGeneric)
            {
                _ = sb.AppendLine($"int _pos = {fieldRef}.Length - _r.Buffer.Length;");
                _ = sb.AppendLine($"var _item = {GenericSerializationUtilFullname}.ReadAnyWithConsumed<{itemType}>({fieldRef}.Slice(_pos), out int _consumed);");
                _ = sb.AppendLine($"_r = new CborReader({fieldRef}.Span.Slice(_pos + _consumed));");
                _ = sb.AppendLine("_list.Add(_item);");
            }
            else if (IsPrimitiveType(cleanItemType))
            {
                _ = EmitPrimitiveListItemRead(sb, cleanItemType, fieldRef);
            }
            else
            {
                _ = sb.AppendLine($"int _pos = {fieldRef}.Length - _r.Buffer.Length;");
                _ = sb.AppendLine($"var _item = ({itemType}){cleanItemType}.Read({fieldRef}.Slice(_pos), out int _consumed);");
                _ = sb.AppendLine($"_r = new CborReader({fieldRef}.Span.Slice(_pos + _consumed));");
                _ = sb.AppendLine("_list.Add(_item);");
            }

            _ = sb.AppendLine("if (_size > 0) _remaining--;");
            _ = sb.AppendLine("}");
            _ = sb.AppendLine("if (_size == -1 && _r.Buffer.Length > 0 && _r.Buffer[0] == 0xFF) _r.ReadDataItem();");
            _ = sb.AppendLine("return _list;");
            _ = sb.AppendLine("}");
            _ = sb.AppendLine("}");

            return sb;
        }

        private static StringBuilder EmitPrimitiveListItemRead(StringBuilder sb, string cleanItemType, string fieldRef)
        {
            switch (cleanItemType)
            {
                case "bool":
                    _ = sb.AppendLine("_list.Add(_r.ReadBoolean());");
                    break;
                case "int":
                    _ = sb.AppendLine("_list.Add(_r.ReadInt32());");
                    break;
                case "uint":
                    _ = sb.AppendLine("_list.Add(_r.ReadUInt32());");
                    break;
                case "long":
                    _ = sb.AppendLine("_list.Add(_r.ReadInt64());");
                    break;
                case "ulong":
                    _ = sb.AppendLine("_list.Add(_r.ReadUInt64());");
                    break;
                case "float":
                    _ = sb.AppendLine("_list.Add(_r.ReadSingle());");
                    break;
                case "double":
                    _ = sb.AppendLine("_list.Add(_r.ReadDouble());");
                    break;
                case "decimal":
                    _ = sb.AppendLine("_list.Add(_r.ReadDecimal());");
                    break;
                case "string":
                    _ = sb.AppendLine("_list.Add(_r.ReadString());");
                    break;
                case "byte[]":
                    _ = sb.AppendLine("_list.Add(_r.ReadByteStringToArray());");
                    break;
                case "ReadOnlyMemory<byte>":
                case "System.ReadOnlyMemory<byte>":
                case "global::System.ReadOnlyMemory<byte>":
                    _ = sb.AppendLine("_list.Add((ReadOnlyMemory<byte>)_r.ReadByteStringToArray());");
                    break;
                case "CborEncodedValue":
                case "Chrysalis.Codec.Types.CborEncodedValue":
                case "global::Chrysalis.Codec.Types.CborEncodedValue":
                    _ = sb.AppendLine("{");
                    _ = sb.AppendLine($"int _pos = {fieldRef}.Length - _r.Buffer.Length;");
                    _ = sb.AppendLine("var _span = _r.ReadDataItem();");
                    _ = sb.AppendLine($"_list.Add(new {CborEncodeValueFullName}({fieldRef}.Slice(_pos, _span.Length)));");
                    _ = sb.AppendLine("}");
                    break;
                case "CborLabel":
                case "Chrysalis.Codec.Types.CborLabel":
                case "global::Chrysalis.Codec.Types.CborLabel":
                    _ = sb.AppendLine("_list.Add(_r.GetCurrentDataItemType() switch");
                    _ = sb.AppendLine("{");
                    _ = sb.AppendLine("    CborDataItemType.Unsigned or CborDataItemType.Signed => new Chrysalis.Codec.Types.CborLabel(_r.ReadInt64()),");
                    _ = sb.AppendLine("    CborDataItemType.String => new Chrysalis.Codec.Types.CborLabel(_r.ReadString()),");
                    _ = sb.AppendLine("    _ => throw new InvalidOperationException($\"Invalid CBOR type for Label: {_r.GetCurrentDataItemType()}\")");
                    _ = sb.AppendLine("});");
                    break;
                default:
                    break;
            }

            return sb;
        }

        private static StringBuilder EmitMapPartialProperty(StringBuilder sb, SerializablePropertyMetadata prop, string fieldRef, string fqType)
        {
            string keyType = prop.MapKeyTypeFullName!;
            string valueType = prop.MapValueTypeFullName!;
            string cleanKeyType = keyType.Replace("?", "");
            string cleanValueType = valueType.Replace("?", "");

            _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName}");
            _ = sb.AppendLine("{");
            _ = sb.AppendLine("get");
            _ = sb.AppendLine("{");

            if (prop.IsTypeNullable)
            {
                _ = sb.AppendLine($"if ({fieldRef}.Length == 0 || {fieldRef}.Span[0] is 0xF6 or 0xF7) return default;");
            }

            _ = sb.AppendLine($"var _r = new CborReader({fieldRef}.Span);");
            _ = sb.AppendLine("_r.ReadBeginMap();");
            _ = sb.AppendLine("int _size = _r.ReadSize();");

            if (IsReadOnlyMemoryByteType(keyType))
            {
                _ = sb.AppendLine($"var _map = new global::System.Collections.Generic.Dictionary<{keyType}, {valueType}>(global::Chrysalis.Codec.Serialization.Utils.ReadOnlyMemoryComparer.Instance);");
            }
            else
            {
                _ = sb.AppendLine($"var _map = new global::System.Collections.Generic.Dictionary<{keyType}, {valueType}>();");
            }

            _ = sb.AppendLine("int _remaining = _size;");
            _ = sb.AppendLine("while (_size == -1 ? (_r.Buffer.Length > 0 && _r.Buffer[0] != 0xFF) : _remaining > 0)");
            _ = sb.AppendLine("{");

            // Read key
            if (prop.IsMapKeyTypeOpenGeneric)
            {
                _ = sb.AppendLine($"int _kPos = {fieldRef}.Length - _r.Buffer.Length;");
                _ = sb.AppendLine($"var _key = {GenericSerializationUtilFullname}.ReadAnyWithConsumed<{keyType}>({fieldRef}.Slice(_kPos), out int _kConsumed);");
                _ = sb.AppendLine($"_r = new CborReader({fieldRef}.Span.Slice(_kPos + _kConsumed));");
            }
            else if (IsPrimitiveType(cleanKeyType))
            {
                _ = EmitPrimitiveMapKeyRead(sb, cleanKeyType, fieldRef);
            }
            else
            {
                _ = sb.AppendLine($"int _kPos = {fieldRef}.Length - _r.Buffer.Length;");
                _ = sb.AppendLine($"var _key = ({keyType}){cleanKeyType}.Read({fieldRef}.Slice(_kPos), out int _kConsumed);");
                _ = sb.AppendLine($"_r = new CborReader({fieldRef}.Span.Slice(_kPos + _kConsumed));");
            }

            // Read value
            if (prop.IsMapValueTypeOpenGeneric)
            {
                _ = sb.AppendLine($"int _vPos = {fieldRef}.Length - _r.Buffer.Length;");
                _ = sb.AppendLine($"var _val = {GenericSerializationUtilFullname}.ReadAnyWithConsumed<{valueType}>({fieldRef}.Slice(_vPos), out int _vConsumed);");
                _ = sb.AppendLine($"_r = new CborReader({fieldRef}.Span.Slice(_vPos + _vConsumed));");
            }
            else if (IsPrimitiveType(cleanValueType))
            {
                _ = EmitPrimitiveMapValueRead(sb, cleanValueType, fieldRef);
            }
            else
            {
                _ = sb.AppendLine($"int _vPos = {fieldRef}.Length - _r.Buffer.Length;");
                _ = sb.AppendLine($"var _val = ({valueType}){cleanValueType}.Read({fieldRef}.Slice(_vPos), out int _vConsumed);");
                _ = sb.AppendLine($"_r = new CborReader({fieldRef}.Span.Slice(_vPos + _vConsumed));");
            }

            _ = sb.AppendLine("if (!_map.ContainsKey(_key))");
            _ = sb.AppendLine("{");
            _ = sb.AppendLine("_map.Add(_key, _val);");
            _ = sb.AppendLine("}");
            _ = sb.AppendLine("if (_size > 0) _remaining--;");
            _ = sb.AppendLine("}");
            _ = sb.AppendLine("if (_size == -1 && _r.Buffer.Length > 0 && _r.Buffer[0] == 0xFF) _r.ReadDataItem();");
            _ = sb.AppendLine("return _map;");
            _ = sb.AppendLine("}");
            _ = sb.AppendLine("}");

            return sb;
        }

        private static StringBuilder EmitPrimitiveMapKeyRead(StringBuilder sb, string cleanKeyType, string fieldRef)
        {
            switch (cleanKeyType)
            {
                case "bool":
                    _ = sb.AppendLine("var _key = _r.ReadBoolean();");
                    break;
                case "int":
                    _ = sb.AppendLine("var _key = _r.ReadInt32();");
                    break;
                case "uint":
                    _ = sb.AppendLine("var _key = _r.ReadUInt32();");
                    break;
                case "long":
                    _ = sb.AppendLine("var _key = _r.ReadInt64();");
                    break;
                case "ulong":
                    _ = sb.AppendLine("var _key = _r.ReadUInt64();");
                    break;
                case "float":
                    _ = sb.AppendLine("var _key = _r.ReadSingle();");
                    break;
                case "double":
                    _ = sb.AppendLine("var _key = _r.ReadDouble();");
                    break;
                case "decimal":
                    _ = sb.AppendLine("var _key = _r.ReadDecimal();");
                    break;
                case "string":
                    _ = sb.AppendLine("var _key = _r.ReadString();");
                    break;
                case "byte[]":
                    _ = sb.AppendLine("var _key = _r.ReadByteStringToArray();");
                    break;
                case "ReadOnlyMemory<byte>":
                case "System.ReadOnlyMemory<byte>":
                case "global::System.ReadOnlyMemory<byte>":
                    _ = sb.AppendLine("var _key = (ReadOnlyMemory<byte>)_r.ReadByteStringToArray();");
                    break;
                case "CborEncodedValue":
                case "Chrysalis.Codec.Types.CborEncodedValue":
                case "global::Chrysalis.Codec.Types.CborEncodedValue":
                    _ = sb.AppendLine("{");
                    _ = sb.AppendLine($"int _kPos = {fieldRef}.Length - _r.Buffer.Length;");
                    _ = sb.AppendLine("var _span = _r.ReadDataItem();");
                    _ = sb.AppendLine($"var _key = new {CborEncodeValueFullName}({fieldRef}.Slice(_kPos, _span.Length));");
                    break;
                case "CborLabel":
                case "Chrysalis.Codec.Types.CborLabel":
                case "global::Chrysalis.Codec.Types.CborLabel":
                    _ = sb.AppendLine("var _key = _r.GetCurrentDataItemType() switch");
                    _ = sb.AppendLine("{");
                    _ = sb.AppendLine("    CborDataItemType.Unsigned or CborDataItemType.Signed => new Chrysalis.Codec.Types.CborLabel(_r.ReadInt64()),");
                    _ = sb.AppendLine("    CborDataItemType.String => new Chrysalis.Codec.Types.CborLabel(_r.ReadString()),");
                    _ = sb.AppendLine("    _ => throw new InvalidOperationException($\"Invalid CBOR type for Label: {_r.GetCurrentDataItemType()}\")");
                    _ = sb.AppendLine("};");
                    break;
                default:
                    break;
            }

            return sb;
        }

        private static StringBuilder EmitPrimitiveMapValueRead(StringBuilder sb, string cleanValueType, string fieldRef)
        {
            switch (cleanValueType)
            {
                case "bool":
                    _ = sb.AppendLine("var _val = _r.ReadBoolean();");
                    break;
                case "int":
                    _ = sb.AppendLine("var _val = _r.ReadInt32();");
                    break;
                case "uint":
                    _ = sb.AppendLine("var _val = _r.ReadUInt32();");
                    break;
                case "long":
                    _ = sb.AppendLine("var _val = _r.ReadInt64();");
                    break;
                case "ulong":
                    _ = sb.AppendLine("var _val = _r.ReadUInt64();");
                    break;
                case "float":
                    _ = sb.AppendLine("var _val = _r.ReadSingle();");
                    break;
                case "double":
                    _ = sb.AppendLine("var _val = _r.ReadDouble();");
                    break;
                case "decimal":
                    _ = sb.AppendLine("var _val = _r.ReadDecimal();");
                    break;
                case "string":
                    _ = sb.AppendLine("var _val = _r.ReadString();");
                    break;
                case "byte[]":
                    _ = sb.AppendLine("var _val = _r.ReadByteStringToArray();");
                    break;
                case "ReadOnlyMemory<byte>":
                case "System.ReadOnlyMemory<byte>":
                case "global::System.ReadOnlyMemory<byte>":
                    _ = sb.AppendLine("var _val = (ReadOnlyMemory<byte>)_r.ReadByteStringToArray();");
                    break;
                case "CborEncodedValue":
                case "Chrysalis.Codec.Types.CborEncodedValue":
                case "global::Chrysalis.Codec.Types.CborEncodedValue":
                    _ = sb.AppendLine("{");
                    _ = sb.AppendLine($"int _vPos = {fieldRef}.Length - _r.Buffer.Length;");
                    _ = sb.AppendLine("var _span = _r.ReadDataItem();");
                    _ = sb.AppendLine($"var _val = new {CborEncodeValueFullName}({fieldRef}.Slice(_vPos, _span.Length));");
                    break;
                case "CborLabel":
                case "Chrysalis.Codec.Types.CborLabel":
                case "global::Chrysalis.Codec.Types.CborLabel":
                    _ = sb.AppendLine("var _val = _r.GetCurrentDataItemType() switch");
                    _ = sb.AppendLine("{");
                    _ = sb.AppendLine("    CborDataItemType.Unsigned or CborDataItemType.Signed => new Chrysalis.Codec.Types.CborLabel(_r.ReadInt64()),");
                    _ = sb.AppendLine("    CborDataItemType.String => new Chrysalis.Codec.Types.CborLabel(_r.ReadString()),");
                    _ = sb.AppendLine("    _ => throw new InvalidOperationException($\"Invalid CBOR type for Label: {_r.GetCurrentDataItemType()}\")");
                    _ = sb.AppendLine("};");
                    break;
                default:
                    break;
            }

            return sb;
        }

        private static StringBuilder EmitPrimitivePartialProperty(StringBuilder sb, SerializablePropertyMetadata prop, string cleanType, string fieldRef, string fqType)
        {
            // For nullable primitives, add CBOR null check
            string nullGuard = prop.IsTypeNullable ? $"{fieldRef}.Length == 0 || {fieldRef}.Span[0] is 0xF6 or 0xF7 ? default({fqType}) : " : "";

            switch (cleanType)
            {
                case "bool":
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName} {{ get => {nullGuard}new CborReader({fieldRef}.Span).ReadBoolean(); }}");
                    break;
                case "int":
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName} {{ get => {nullGuard}new CborReader({fieldRef}.Span).ReadInt32(); }}");
                    break;
                case "uint":
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName} {{ get => {nullGuard}new CborReader({fieldRef}.Span).ReadUInt32(); }}");
                    break;
                case "long":
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName} {{ get => {nullGuard}new CborReader({fieldRef}.Span).ReadInt64(); }}");
                    break;
                case "ulong":
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName} {{ get => {nullGuard}new CborReader({fieldRef}.Span).ReadUInt64(); }}");
                    break;
                case "float":
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName} {{ get => {nullGuard}new CborReader({fieldRef}.Span).ReadSingle(); }}");
                    break;
                case "double":
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName} {{ get => {nullGuard}new CborReader({fieldRef}.Span).ReadDouble(); }}");
                    break;
                case "decimal":
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName} {{ get => {nullGuard}new CborReader({fieldRef}.Span).ReadDecimal(); }}");
                    break;
                case "string":
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName} {{ get => {nullGuard}new CborReader({fieldRef}.Span).ReadString(); }}");
                    break;
                case "byte[]":
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName} {{ get => {nullGuard}new CborReader({fieldRef}.Span).ReadByteStringToArray(); }}");
                    break;
                case "ReadOnlyMemory<byte>":
                case "System.ReadOnlyMemory<byte>":
                case "global::System.ReadOnlyMemory<byte>":
                    // Zero-copy: read the byte string header to find content offset, then slice
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName}");
                    _ = sb.AppendLine("{");
                    _ = sb.AppendLine("get");
                    _ = sb.AppendLine("{");
                    if (prop.IsTypeNullable)
                    {
                        _ = sb.AppendLine($"if ({fieldRef}.Length == 0 || {fieldRef}.Span[0] is 0xF6 or 0xF7) return default;");
                    }
                    _ = sb.AppendLine($"var _r = new CborReader({fieldRef}.Span);");
                    _ = sb.AppendLine("bool _isIndef = _r.Buffer.Length > 0 && _r.Buffer[0] == 0x5F;");
                    _ = sb.AppendLine("if (_isIndef) return (ReadOnlyMemory<byte>)_r.ReadByteStringToArray();");
                    _ = sb.AppendLine("ReadOnlySpan<byte> _bs = _r.ReadByteString();");
                    _ = sb.AppendLine($"int _after = {fieldRef}.Length - _r.Buffer.Length;");
                    _ = sb.AppendLine($"return {fieldRef}.Slice(_after - _bs.Length, _bs.Length);");
                    _ = sb.AppendLine("}");
                    _ = sb.AppendLine("}");
                    break;
                case "CborEncodedValue":
                case "Chrysalis.Codec.Types.CborEncodedValue":
                case "global::Chrysalis.Codec.Types.CborEncodedValue":
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName} {{ get => {nullGuard}new {CborEncodeValueFullName}({fieldRef}); }}");
                    break;
                case "CborLabel":
                case "Chrysalis.Codec.Types.CborLabel":
                case "global::Chrysalis.Codec.Types.CborLabel":
                    _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName}");
                    _ = sb.AppendLine("{");
                    _ = sb.AppendLine("get");
                    _ = sb.AppendLine("{");
                    _ = sb.AppendLine($"var _r = new CborReader({fieldRef}.Span);");
                    _ = sb.AppendLine("return _r.GetCurrentDataItemType() switch");
                    _ = sb.AppendLine("{");
                    _ = sb.AppendLine("    CborDataItemType.Unsigned or CborDataItemType.Signed => new Chrysalis.Codec.Types.CborLabel(_r.ReadInt64()),");
                    _ = sb.AppendLine("    CborDataItemType.String => new Chrysalis.Codec.Types.CborLabel(_r.ReadString()),");
                    _ = sb.AppendLine("    _ => throw new InvalidOperationException($\"Invalid CBOR type for Label: {_r.GetCurrentDataItemType()}\")");
                    _ = sb.AppendLine("};");
                    _ = sb.AppendLine("}");
                    _ = sb.AppendLine("}");
                    break;
                default:
                    break;
            }

            return sb;
        }

        private static StringBuilder EmitMaybeIndefListPartialProperty(StringBuilder sb, SerializablePropertyMetadata prop, string fieldRef, string fqType)
        {
            string itemFqn = prop.CborMaybeIndefListItemTypeFullName!;
            string cleanItemFqn = itemFqn.Replace("?", "");
            string nonNullType = fqType.Replace("?", "");

            _ = sb.AppendLine($"public partial {fqType} {prop.PropertyName}");
            _ = sb.AppendLine("{");
            _ = sb.AppendLine("get");
            _ = sb.AppendLine("{");

            if (prop.IsTypeNullable)
            {
                _ = sb.AppendLine($"if ({fieldRef}.Length == 0 || {fieldRef}.Span[0] is 0xF6 or 0xF7) return default;");
            }

            // Emit cache registration for the item type
            string? primitiveReaderRef = GetPrimitiveReaderRef(cleanItemFqn);
            if (primitiveReaderRef != null)
            {
                _ = sb.AppendLine($"global::Chrysalis.Codec.Serialization.CborListReaderCache<{itemFqn}>.Reader ??= {primitiveReaderRef};");
            }
            else
            {
                _ = sb.AppendLine($"global::Chrysalis.Codec.Serialization.CborListReaderCache<{itemFqn}>.Reader ??= {cleanItemFqn}.Read;");
            }

            _ = sb.AppendLine($"return {nonNullType}.Read({fieldRef});");
            _ = sb.AppendLine("}");
            _ = sb.AppendLine("}");

            return sb;
        }

        private static string? GetPrimitiveReaderRef(string cleanType)
        {
            const string prefix = "global::Chrysalis.Codec.Serialization.CborPrimitiveReaders";
            return cleanType switch
            {
                "int" => $"{prefix}.ReadInt32",
                "uint" => $"{prefix}.ReadUInt32",
                "long" => $"{prefix}.ReadInt64",
                "ulong" => $"{prefix}.ReadUInt64",
                "bool" => $"{prefix}.ReadBoolean",
                "string" => $"{prefix}.ReadString",
                "float" => $"{prefix}.ReadSingle",
                "double" => $"{prefix}.ReadDouble",
                "byte[]" => $"{prefix}.ReadByteArray",
                "ReadOnlyMemory<byte>" or "System.ReadOnlyMemory<byte>" or "global::System.ReadOnlyMemory<byte>"
                    => $"{prefix}.ReadByteMemory",
                _ => null
            };
        }

        private static ICborSerializerEmitter GetEmitter(SerializableTypeMetadata metadata) => metadata.SerializationType switch
        {
            SerializationType.Constr => new ConstructorEmitter(),
            SerializationType.Container => new ContainerEmitter(),
            SerializationType.List => new ListEmitter(),
            SerializationType.Map => new MapEmitter(),
            SerializationType.Union => new UnionEmitter(),
            _ => throw new NotSupportedException($"Serialization type {metadata.SerializationType} is not supported.")
        };

        public static int ResolveTag(int? index)
        {
            if (index is null or < 0)
            {
                return -1;
            }
            else
            {
                int finalIndex = index > 6 ? 1280 - 7 : 121;
                return finalIndex + index.Value;
            }
        }

        private static bool IsReadOnlyMemoryByteType(string type) => type.Replace("?", "") is "ReadOnlyMemory<byte>" or "System.ReadOnlyMemory<byte>" or "global::System.ReadOnlyMemory<byte>";

        private static bool IsPrimitiveType(string type) => type.Replace("?", "") switch
        {
            "bool" => true,
            "int" => true,
            "long" => true,
            "ulong" => true,
            "uint" => true,
            "float" => true,
            "double" => true,
            "decimal" => true,
            "string" => true,
            "byte[]" => true,
            "ReadOnlyMemory<byte>" => true,
            "System.ReadOnlyMemory<byte>" => true,
            "global::System.ReadOnlyMemory<byte>" => true,
            "CborEncodedValue" => true,
            "Chrysalis.Codec.Types.CborEncodedValue" => true,
            "global::Chrysalis.Codec.Types.CborEncodedValue" => true,
            "CborLabel" => true,
            "Chrysalis.Codec.Types.CborLabel" => true,
            "global::Chrysalis.Codec.Types.CborLabel" => true,
            _ => false
        };
    }
}
