# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  create:
    types: [tag]
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/Chrysalis

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src/Chrysalis

    - name: Test
      run: dotnet test --verbosity normal
      working-directory: ./src/Chrysalis.Test

    - name: Publish
      run: dotnet publish --no-restore
      working-directory: ./src/Chrysalis

    - name: Pack
      run: rm -rf out
      run: dotnet pack --no-build -c Release -o out
      working-directory: ./src/Chrysalis

    - name: Push to NuGet
      run: dotnet nuget push ./src/Chrysalis/out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      if: github.event_name == 'release'